feat: update remote-install
- 在开始就判断文件是否存在
- 安装node 和 安装nodepack 分成两个function，现在，如果不加版本号就只安装 node package
- 增加了远程解包结果的输出

diff --git a/bin/remote-install b/bin/remote-install
--- a/bin/remote-install
+++ b/bin/remote-install
@@ -4,19 +4,51 @@ REMOTEHOST=$1
 VERSION=$2
 NODE=node-$VERSION-linux-x64.tar.xz
 NPM_PACKAGE=npm-global-packs.tgr.xz
-if [ ! $REMOTEHOST ] || [ ! $VERSION ] ; then
+
+
+if [ ! $REMOTEHOST ] ; then
     echo 'Please specific the remote host, for example: "sysinit remote-install user@192.168.123.100 v6.0.0".'
     exit
 fi
 
-echo "copy '$NODE' to remote..."
-scp "download/$NODE" "$REMOTEHOST:~/" &&
-echo "copy node package to remote..." &&
-scp "download/$NPM_PACKAGE" "$REMOTEHOST:~/" &&
-echo "install..." &&
-ssh -t $REMOTEHOST "
-	sudo tar --strip-components 1 -xvf ~/$NODE -C /usr/local
-    sudo tar -xvf $NPM_PACKAGE -C /usr/local
-" &&
-echo "DONE!"
+installNode(){
+	echo "Install Node..."
+	if [ ! -f "download/$NODE" ] ; then
+		echo "'$NODE' not exist, use 'sysinit download-node <version>' command to get one." 
+		exit
+	fi
+
+	echo "copy '$NODE' to remote..."
+	scp "download/$NODE" "$REMOTEHOST:~/" &&
+	echo "install..." &&
+	ssh -t $REMOTEHOST "
+		sudo tar --strip-components 1 -xvf ~/$NODE -C /usr/local && echo 'Node install success.'  || echo 'Node install failed!'
+	" &&
+	echo "Install Node Complete!"
+}
+
+installNpm(){
+	echo "Install Node Package..."
+	if [ ! -f "download/$NPM_PACKAGE" ] ; then
+		echo "'$NPM_PACKAGE' not exist, use 'sysinit node-pack [-g] <package-names ...>' command to get one." 
+		exit
+	fi
+
+	echo "copy node package to remote..." &&
+	scp "download/$NPM_PACKAGE" "$REMOTEHOST:~/" &&
+	echo "install..." &&
+	ssh -t $REMOTEHOST "
+	    sudo tar -xvf $NPM_PACKAGE -C /usr/local && echo 'Node pack install success.' || echo 'Node pack install failed!'
+	" &&
+	echo "Install Node Package Complete!"
+}
+
+if [ $REMOTEHOST ] && [ $VERSION ] ; then
+	installNode
+fi
+
+if [ $REMOTEHOST ] ; then
+	installNpm
+fi
+
     
